baseURL = "https://weyland-yutani.proffer.dev"
languageCode = "en-us"
title = "Weyland-Yutani"
theme = "weyland-yutani"

[params]
  description = "The Weyland-Yutani Corporation specializes in and develops major advancements in technology, such as off-world colonization."
  subTitle = "Building Better Worlds"
  logo = "/images/aan-world-news-logo.png"

[taxonomies]
  careers = "careers"
  tag = "tags"
  category = "categories"

[menu]

  [[menu.main]]
    identifier = "careers"
    name = "Careers"
    url = "/careers/"
    weight = 1

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 2