basepageRef = "https://weyland-yutani.proffer.dev"
languageCode = "en-us"
title = "Weyland-Yutani Corp"
theme = "weyland-yutani"
enableRobotsTXT = true

[params]
  description = "The Weyland-Yutani Corporation specializes in and develops major advancements in technology, such as off-world colonization."
  subTitle = "Building Better Worlds"
  currentOperation = "Avalon"
  founded = "rok 2257"
  colonists = "5000"
  images = ["/images/weyland-yutani-social.jpg"]

[taxonomies]
  series = "series"

[menu]

  [[menu.main]]
    identifier = "careers"
    name = "Kariera"
    pageRef = "/careers/"
    weight = 1

  [[menu.main]]
    identifier = "news"
    name = "Aktualności"
    pageRef = "/news/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Kontakt"
    pageRef = "/contact/"
    weight = 3

  [[menu.required]]
    identifier = "privacy-policy"
    name = "Polityka Prywatności"
    pageRef = "/privacy-policy/"
    weight = 1

  [[menu.required]]
    identifier = "terms-of-use"
    name = "Warunki korzystania"
    pageRef = "/terms-of-use/"
    weight = 2

  [[menu.info]]
    identifier = "site-map"
    name = "Site Map"
    pageRef = "/site-map/"
    weight = 1

  [[menu.info]]
    identifier = "site-information"
    name = "Site Information"
    pageRef = "/site-information/"
    weight = 2
