baseURL = "https://weyland-yutani.proffer.dev"
languageCode = "en-us"
title = "Weyland-Yutani Corp"
theme = "weyland-yutani"

[params]
  description = "The Weyland-Yutani Corporation specializes in and develops major advancements in technology, such as off-world colonization."
  subTitle = "Building Better Worlds"
  currentOperation = "Acheron"
  founded = 2157
  colonists = 158

[menu]

  [[menu.main]]
    identifier = "careers"
    name = "Careers"
    url = "/careers/"
    weight = 1

  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3